### ISSUE TITLE
fix Sonar settings

### ISSUE THREAD

**Issue by lhein** [camel-tooling/generator-camel-project#10]
Currently we get the following error when trying to do sonar analysis. It seems the settings are not fully valid.

`ERROR: Error during SonarQube Scanner execution
org.sonar.java.AnalysisException: Please provide compiled classes of your project with sonar.java.binaries property
	at org.sonar.java.JavaClasspath.init(JavaClasspath.java:57)
	at org.sonar.java.AbstractJavaClasspath.getElements(AbstractJavaClasspath.java:280)
	at org.sonar.java.SonarComponents.getJavaClasspath(SonarComponents.java:190)
	at org.sonar.java.JavaSquid.<init>(JavaSquid.java:85)
	at org.sonar.plugins.java.JavaSquidSensor.execute(JavaSquidSensor.java:92)
	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:45)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:88)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:62)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:74)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:166)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:300)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:295)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:269)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:82)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:131)
	at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:111)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)`

**Comment by bfitzpat** [comment]
@lhein What did you use for the Sonar analysis? I'm doing most of this in VSCode - is there a sonar plug-in for it?

**Comment by bfitzpat** [comment]
I found https://www.sonarlint.org/vscode/ - but that's not the same as getting the sonar stuff running upstream in Qube. What settings do we need for that?

**Comment by bfitzpat** [comment]
Fixed the one issue sonarlint found - https://github.com/camel-tooling/generator-camel-project/pull/19

**Comment by apupier** [comment]
I think that Sonar is detecting the Java files that are in used as templates. They are not compiled (which is normal).
Based on error message, i think that Sonar requires Java files to be compiled to make a n analysis on them. I would try to ignore Java files https://docs.sonarqube.org/display/SONAR/Narrowing+the+Focus

**Comment by bfitzpat** [comment]
Based on the link suggested by @apupier I have created PR https://github.com/camel-tooling/generator-camel-project/pull/20 to try and exclude the java files in the templates from sonar analysis. @lhein does this work?

**Comment by bfitzpat** [comment]
Sonar is now running and reported this - https://sonarcloud.io/project/issues?id=generator-camel-project&resolved=false&types=CODE_SMELL - will fix in a separate PR and then close this issue.

**Comment by bfitzpat** [comment]
Created PR - https://github.com/camel-tooling/generator-camel-project/pull/23 - to fix code smell for package

**Comment by bfitzpat** [comment]
All issues fixed and merged. Closing
